import { Txt2ImageParams } from '@/types';

export const startTxt2ImageParams: Txt2ImageParams = {
    //used
    width: 512,
    height: 512,
    batch_size: 1,
    prompt: '',
    negative_prompt: '',
    steps: 30,
    //unused
    enable_hr: false,
    denoising_strength: 0,
    firstphase_width: 0,
    firstphase_height: 0,
    hr_scale: 2,
    hr_upscaler: 'string',
    hr_second_pass_steps: 0,
    hr_resize_x: 0,
    hr_resize_y: 0,
    styles: ['string'],
    seed: -1,
    subseed: -1,
    subseed_strength: 0,
    seed_resize_from_h: -1,
    seed_resize_from_w: -1,
    sampler_name: '',
    n_iter: 1,
    cfg_scale: 7,
    restore_faces: false,
    tiling: false,
    do_not_save_samples: false,
    do_not_save_grid: false,
    eta: 0,
    s_churn: 0,
    s_tmax: 0,
    s_tmin: 0,
    s_noise: 1,
    override_settings: {},
    override_settings_restore_afterwards: true,
    script_args: [],
    sampler_index: 'Euler',
    script_name: '',
    send_images: true,
    save_images: false,
    alwayson_scripts: {},
  }